[package]
name = "redis-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.48.0", features = ["full"] }
ordered-float = "4.0"
axum = "0.7"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

